### ISSUE TITLE
32位的 QQNT 无法使用

### ISSUE THREAD

**Issue by qixiamg20160** [BetterQQNT/BetterQQNT#10]
将 better-qqnt.dll 重命名为 version.dll 后放到 QQNT 文件夹, 启动不会有任何报错而是单纯不生效

**Comment by yi03** [comment]
> 尝试 Launcher 是否可用？

请问如何使用 Launcher 。我看 koishi 的 qq-launcher 插件还是空的，没有内容。
[这个仓库](https://github.com/BetterQQNT/BetterQQNT-Launcher)我编译完了之后，不知道然后应该做什么了。

**Comment by yi03** [comment]
> > 尝试 Launcher 是否可用？
> 
> 请问如何使用 Launcher 。我看 koishi 的 qq-launcher 插件还是空的，没有内容。 [这个仓库](https://github.com/BetterQQNT/BetterQQNT-Launcher)我依照[这里的方法](https://github.com/BetterQQNT/BetterQQNT-Launcher/blob/master/.github/workflows/build.yml)编译完了之后得到了 bqqenv.exe 文件，然后不知道应该做什么了。直接以管理员身份运行 bqqenv.exe 的话，登录后没有预期的插件。

大概解决了。使用[dll_injector](https://github.com/hasherezade/dll_injector)成功注入了better-qqnt-no-hijack-x64.dll。

**Comment by jackwd387** [comment]
我也出现了这个问题
