### ISSUE TITLE
设置的背景图片被移动或删除后会导致主题背景变灰

### ISSUE THREAD

**Issue by callng** [BetterQQNT/BetterQQNT#11]
我图片放在桌面上的，被误删除后发现主题背景变灰了，恢复后则正常显示。
解决方法1：插件主动把背景图片复制缓存到QQ缓存目录，以后使用缓存目录的图片。
解决方法2：手动把图片放到不会误删除的目录（比如安装目录），再选择背景图片。

**Comment by windy1021** [comment]
还有的图片上传以后背景就变成灰的了，不知道是不是格式问题还是bug
