### ISSUE TITLE
我是SVIP但是我的图片背景修改不生效

### ISSUE THREAD

**Issue by Angelhellwolf** [BetterQQNT/BetterQQNT#17]
在启动的时候会闪一下，然后图片就消失了，在设置中会应用的图片，而聊天界面不显示
我的QQ是年费的SVIP

**Comment by skykeyjoker** [comment]
![image](https://github.com/BetterQQNT/BetterQQNT/assets/17134346/78a8e898-2af6-4ad7-8a77-add910843137)
是否开启了Win10/Win11 Acrylic窗口特效

**Comment by Angelhellwolf** [comment]
解决了，就是我开启了那个窗口特效导致的（x
