### ISSUE TITLE
增强背景覆盖功能

### ISSUE THREAD

**Issue by slqwqxd** [BetterQQNT/BetterQQNT#27]
QQ会使用自带背景替换
更改以下元素可以解决
栗子："<"div class="q-miracle-background miracle-background" data-v-f7b0cfc6="" data-v-2d255bd6="" style="background: url(&quot;https://i.pixiv.re/img-master/img/2022/11/13/00/00/30/102739357_p0_master1200.jpg&quot;) center center / 100% 100% rgb(50, 50, 50);"><div class="q-miracle-background__texture_area" data-v-f7b0cfc6="" style="opacity: 0; mix-blend-mode: overlay; background-image: url(&quot;https://i.pixiv.re/img-master/img/2022/11/13/00/00/30/102739357_p0_master1200.jpg&quot;);"></div>"</div>"
![456f7501231134d1128186d8fc2b54f2](https://github.com/BetterQQNT/BetterQQNT/assets/109799548/536b6da0-9f50-4a4c-a69a-e5d5c933df78)
![5e57a73b43cae3c33e3a43522c845a8c](https://github.com/BetterQQNT/BetterQQNT/assets/109799548/eef202d9-641e-4cb5-bc22-267ecc150b80)

本更改与亚克力效果无关

**Comment by slqwqxd** [comment]
还有devtools被锁了，不好玩（

**Comment by MengNianxiaoyao** [comment]
f11，按这个就能开

**Comment by slqwqxd** [comment]
还有选旧版的透明类主题的话

**Comment by slqwqxd** [comment]
可以直接改messages-panel的背景实现全局覆盖
