### ISSUE TITLE
群聊界面侧栏（群公告、群成员）无法收起

### ISSUE THREAD

**Issue by skykeyjoker** [BetterQQNT/BetterQQNT#3]
![1](https://github.com/koishi-nt/BetterQQNT/assets/17134346/4bc5e308-2580-4b39-a61d-74bf49377350)
如图所示，群聊界面侧栏无法点击收起

**Comment by ShadyWhite** [comment]
在主题模式中时

**Comment by skykeyjoker** [comment]
依旧存在
