### ISSUE TITLE
在QQNT版本9.8.5-14060 (Windows, x64) 无法正常注入：无法定位程序输入点 于动态链接库 <path>.dll上

### ISSUE THREAD

**Issue by maxesisn** [BetterQQNT/BetterQQNT#30]
QQNT版本：9.8.5-14060 (Windows, x64)
BetterQQNT版本：0.2.0
使用DLL Hijacking方法：
![image](https://github.com/BetterQQNT/BetterQQNT/assets/20412597/d2db8e3b-16b5-437b-8f83-0900a959e78c)
使用Launcher:
![image](https://github.com/BetterQQNT/BetterQQNT/assets/20412597/60e6762c-8684-4e84-aed7-3ed9f88b6b72)

QQNT版本截图：
![image](https://github.com/BetterQQNT/BetterQQNT/assets/20412597/109e72cf-4cee-4cc7-88ed-62cb1940ad93)

**Comment by MicroCBer** [comment]
请看最新版release note
