### ISSUE TITLE
QQNT 9.8.5疑似加强了代码保护使BetterQQNT无法运行

### ISSUE THREAD

**Issue by WhatDamon** [BetterQQNT/BetterQQNT#31]
这段时间发布Windows版QQNT 9.8.5似乎通过修改electron源码导致**现阶段所有QQNT插件（包括BetterQQNT）失效**，包括开发者工具也被完全禁用，其他偏门方式统统无效，代码保护措施进一步加强
在可预见的未来，QQNT的代码保护只会越来越严，不知BetterQQNT如何处理
（附：注入JavaScript、TypeScript也无效）

-----

目前使用最新版的BetterQQNT在该QQNT版本会报VERSION.DLL错误，删除后问题接触

**Comment by MicroCBer** [comment]
这是正常现象，请见 release 界面
