### ISSUE TITLE
现在koishi控制台的日志似乎看不到聊天记录

### ISSUE THREAD

**Issue by yi03** [BetterQQNT/BetterQQNT#37]
现在koishi控制台的日志似乎看不到聊天记录。以前把gocq插件的日志等级调高日志里就能显示聊天记录了，但是用ntqq插件启动koishi机器人的话，我没找到这种选项。

**Comment by ilharp** [comment]
日志输出聊天记录是 go-cqhttp 而非平台适配器的行为，在新版中我们已经默认禁用了这个行为。输出聊天记录的需求与特定的适配器或平台无关，需要在日志中显示聊天记录可以安装 `messages` 和 `message-logger` 两个插件。

如果你在使用上述两个插件的过程中遇到了问题，可以前往 Koishi 论坛发帖求助。
