### ISSUE TITLE
无法自定义壁纸

### ISSUE THREAD

**Issue by yw2048** [BetterQQNT/BetterQQNT#4]
在qq版本: 9.8.3 (13183)中更改壁纸之后变成空白壁纸，使用的是0.1.1版本的better-qqnt.dll。
同时发现0.1.1版本的better-qqnt-no-hijack.dll无法打开QQ，显现如下：
![Quicker_20230603_172248](https://github.com/koishi-nt/BetterQQNT/assets/89087607/d86f62e7-1758-455d-b56e-1f326222f71c)

**Comment by MicroCBer** [comment]
你有svip吗

**Comment by MicroCBer** [comment]
no hijack是给launcher用的 不能改成version.dll

**Comment by yw2048** [comment]
> 你有vip吗

没有，但是刚开始进去会有一个蓝色的默认主题，自己更改就会出错，不懂为什么不是vip也有个壁纸

**Comment by MicroCBer** [comment]
啊？不是vip也能用主题？

**Comment by yw2048** [comment]
> 啊？不是vip也能用主题？

对呀，我也很奇怪，我还以为那个只能给QQ会员使用是骗tx的

**Comment by MicroCBer** [comment]
完了写出bug了 马上改

**Comment by windy1021** [comment]
> 完了写出bug了 马上改

气抖冷，网易云不是会员也能换壁纸，为什么QQ不行😭😭😭

**Comment by windy1021** [comment]
> > 你有vip吗
> 
> 没有，但是刚开始进去会有一个蓝色的默认主题，自己更改就会出错，不懂为什么不是vip也有个壁纸

我也不是会员，我改壁纸可以改诶，你换到暗色主题试试

**Comment by MicroCBer** [comment]
好了 现在不是svip不给用了
