### ISSUE TITLE
QQ崩溃

### ISSUE THREAD

**Issue by shoucandanghehe** [BetterQQNT/BetterQQNT#5]
~~似乎是发生在定位被撤回的消息时~~ 并不是

![image](https://github.com/koishi-nt/BetterQQNT/assets/51957264/c61cf45c-c172-4ced-b0b6-11409e2a5772)

日志和转储文件👇
[QQ5e049a8.txt](https://github.com/koishi-nt/BetterQQNT/files/11642364/QQ5e049a8.txt)
[QQ5e049a8MidDump.zip](https://github.com/koishi-nt/BetterQQNT/files/11642365/QQ5e049a8MidDump.zip)

QQ版本 9.8.3（13183）

**Comment by MicroCBer** [comment]
下个版本做一下关闭防撤回 再看看能不能复现

**Comment by MicroCBer** [comment]
请尝试关闭防撤回后是否能复现

**Comment by shoucandanghehe** [comment]
> 请尝试关闭防撤回后是否能复现

![image](https://github.com/BetterQQNT/BetterQQNT/assets/51957264/d57671a5-b5f7-48a9-ad8d-90110ec5e805)

复现成功 看来不是防撤回的锅

**Comment by yi03** [comment]
找到了一个很粗略的复现崩溃的流程，短时间内复现成功了七八次了。
用的这个[BetterQQNT-Launcher](https://github.com/BetterQQNT/BetterQQNT-Launcher/releases/download/0.1.4/bqqenv-x64.exe)，QQ版本是9.8.3 (13183) 64位。windows 11最新版本。

不停的到各个群点开图片，在同一个群里点开很多图片似乎没用？反正就是到各个不同群点开图片，一般点开十张左右的图片就会崩溃了。

**Comment by shoucandanghehe** [comment]
我现在开图片会崩 翻记录会崩 有时候放着就崩了）

**Comment by yi03** [comment]
> 我现在开图片会崩 翻记录会崩 有时候放着就崩了）

我用0.1.4登了一晚上，暂时只在点开图片的时候崩了，其他情况暂时还没崩。

**Comment by shoucandanghehe** [comment]
> > 我现在开图片会崩 翻记录会崩 有时候放着就崩了）
> 
> 我用 0.1.4 登了一晚上，暂时只在点开图片的时候崩了，其他情况暂时还没崩。

更了下0.1.4
现在错误号变了（
736CC563146E8F03150086CCA08DB212
[Dump.zip](https://github.com/BetterQQNT/BetterQQNT/files/11675734/Dump.zip)

**Comment by qianbimo** [comment]
我也出现了相同问题，
1.打开一个群定位之前的信息会出现崩溃
2.开关防撤回有没有用
3.打开图片时有一定概率崩溃
4.有的时候发消息都会崩溃|
这个是崩溃日志

[QQ414dd69.zip](https://github.com/BetterQQNT/BetterQQNT/files/11685228/QQ414dd69.zip)

**Comment by KasumiNova** [comment]
同样有此问题。
[QQb2c59e0.zip](https://github.com/BetterQQNT/BetterQQNT/files/11815217/QQb2c59e0.zip)

**Comment by MicroCBer** [comment]
fixed in 0.3.0
