### ISSUE TITLE
64 位的 QQNT 无法使用

### ISSUE THREAD

**Issue by MianSoft** [BetterQQNT/BetterQQNT#7]
无论是用 [手动安装](https://github.com/BetterQQNT/BetterQQNT#%E6%89%8B%E5%8A%A8%E5%AE%89%E8%A3%85)(将 better-qqnt.dll 重命名为 version.dll 后放到 QQNT 文件夹) 还是[使用 BetterQQNT-Launcher](https://github.com/BetterQQNT/BetterQQNT#%E4%BD%BF%E7%94%A8-betterqqnt-launcher)(手动构建不是自动构建) 来安装都不行，启动不会有任何报错而是单纯不生效
使用 32 位后就正常了
顺便附上 64 位链接:https://qqpatch.gtimg.cn/fullUpdate/release/win64/9.8.3-13183/QQ-NT-9.8.3-13183-win64.exe

**Comment by fatinghenji** [comment]
same

**Comment by MianSoft** [comment]
9.8.3-13456的链接:https://dldir1.qq.com/qqfile/qq/QQNT/b82c6358/QQ9.8.3.13456_x64.exe

**Comment by MianSoft** [comment]
感觉内置更新有俩频道一个 64 一个 32 的。看群友 32 的早就收到更新弹窗了，64 根本莫得，直到我看群才知道更新了....

**Comment by MianSoft** [comment]
好好好 辛苦了
